import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="bg-home-gradient">
				<header className="sticky top-0 z-50">
					<div className="text-red-300">Dog Leads</div>
				</header>
				{children}
			</body>
		</html>
	);
}
